language: node_js
node_js:
- '4.1'
install: npm install
script: gulp tests
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: ZOUncOhQPR9iTH8fSCA/9nvgbQeJtiJ0iCHLwTxFqZTp4Q3GWTUQU+9cqdyz/jpCc2flq3n2RDrpxquQkjZGbsfpEHX0Fn0qX9i1eusbFDfsIDaD/ud9PTx07XBZxs/8gdTEB4lIt3ShpQ/AiLc1T/TSqAUGprcdr7yu+KWauxQ3O8HidKYh1fHvlI4JOh+AQgq87ewRg0fw7pZe+jzfCD/T478kBoonEtiHGiXfZo8dgmrk5XjX6okuaHaK9VoCz4RoFroxZcUVGi5agrGcPE29V8qqMPY1lRzFZjFCTqVNCjP3s1YcKh3iqd4WU6ScFKHXLJRdoTk6uG5PitGHM+ZozxIZU5zwNmkV153wERkyfOmRee8KaqN/vLyLJf29A7fupL1QaKVb6oBPqx7rd6IjoYJ9QNNBIPNvIUnU2NINYZ9iigJbWVTpn59aHFac+ktSlxfOpF3cyZH1IC/uRV6M3slb82KUB+Of/yGNX47igHchvdja8WUPVg/2jy4+MbRjkaWGC7zVuAdw4SFEvs2e54lkggnH87Urt+nxKwDDMkGL6aYoVN0xaIbOQ8t2LeHi+RbUdCFgFJ9+Ns6GjCvRbAv006dcyMO1WCiwmOONaZqqJMu9/gsr4usJ1t4LMZld7SHqA4roazl3SQtk3Cp+FiCsmxxgMhjCHpnnK+0=
